networks: 
  nginx-jwk-net:

services:
  access:
    build: 
      dockerfile: Dockerfile
      context: ./access
    networks:
      - nginx-jwk-net
  kc:
    build:
      dockerfile: ./keycloak/Dockerfile
    ports:
      - 8080:8080
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    environment:
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - nginx-jwk-net
  nginx:
    depends_on:
      - kc
      - access
    build:
      network: host
      context: ./nginx
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./nginx/etc/js:/etc/nginx/js
    networks:
      - nginx-jwk-net
    ports:
      - 58080:6000
