networks: 
  nginx-jwk-net:

services:
  microservice-a:
    build: 
      dockerfile: Dockerfile
      context: ./microservice-a
    networks:
      - nginx-jwk-net
  microservice-b:
    build: 
      dockerfile: Dockerfile
      context: ./microservice-b
    networks:
      - nginx-jwk-net
  signer: 
    build: 
      dockerfile: Dockerfile
      context: ./signer
    networks:
      - nginx-jwk-net
  nginx:
    depends_on:
      - signer
      - microservice-a
      - microservice-b
    build:
      network: host
      context: ./nginx
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./nginx/etc/js:/etc/nginx/js
    networks:
      - nginx-jwk-net
    ports:
      - 58080:8000
